MAX_RECORD_SIZE_PER_PAGE = 120
MAX_WORKERS = 10
NO_RECORD_FOUND = object()
PENDING_FETCH = object()

COLLECTIONS = [
    'NEW_FREE',
    'NEW_PAID',
    'TOP_FREE',
    'TOP_PAID',
    'TOP_GROSSING',
    'TRENDING'
]

CATEGORIES = [
    "GAME",
    "GAME_ACTION",
    "GAME_ADVENTURE",
    "GAME_ARCADE",
    "GAME_BOARD",
    "GAME_CARD",
    "GAME_CASINO",
    "GAME_CASUAL",
    "GAME_EDUCATIONAL",
    "GAME_MUSIC",
    "GAME_PUZZLE",
    "GAME_RACING",
    "GAME_ROLE_PLAYING",
    "GAME_SIMULATION",
    "GAME_SPORTS",
    "GAME_STRATEGY",
    "GAME_TRIVIA",
    "GAME_WORD"
]